#!/bin/bash
set -euo pipefail

bufferdir=/tmp/mybuffer
mkdir -p /tmp/mybuffer

curl() {
	local n
	n=$bufferdir/$(echo "$1" | sed 's;^http://;;')/index.html
	echo "wget --continue \"$1\" -O \"$n\"" >&2
	if [ ! -s "$n" ]; then
		mkdir -p $(dirname $n)
		wget --continue "$1" -O $n
	fi
	cat $n
}

links=$(curl http://www.cplusplus.com/reference/algorithm/ \
	| xmllint --html --xpath '//dl[@class="links"]//a/@href' - 2>/dev/null \
	| sed 's/ href="/\n/g' | sed -e '/^[[:space:]]*$/d' -e 's/"$//' -e 's;^;http://www.cplusplus.com;')

echo "$links" >&2

cat <<EOF
/**
 * Autogenerated by $0 script
 */
EOF

for l in $links; do
	{
	echo "// Code from $l"
	i=$(curl "$l" | xmllint --html --xpath '//td[@class="source"]//code' - 2>/dev/null)
	echo "$i" \
		| sed -e 's/&lt;/</g' -e 's/<[\/]\?[a-z]*>//g' -e 's/&gt;/>/g' -e 's/&amp;/&/' \
		| grep -B100 '^#' | grep -v '^#'
	echo
	} | tee /dev/stderr
done
